[package]
name = "secret_contract_example"
version = "0.1.0"
authors = ["SecretTemplateExample"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
schema = ["cosmwasm-schema"]

[dependencies]
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
schemars = "0.8.11"
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", rev = "f7e2b1dbf11e113e258d796288752503a5012367" }
cosmwasm-storage = { git = "https://github.com/scrtlabs/cosmwasm", rev = "f7e2b1dbf11e113e258d796288752503a5012367" }
cw-storage-plus = { version = "0.14.0", default-features = false }

# Used only for schema generation
cosmwasm-schema = { version = "1.1.0", optional = true }

# Uncomment these for some common extra tools
secret-toolkit-crypto = { version = "0.6.0", features = ["rand", "hash"]}

# custom deps
base32 = "0.4.0"
thiserror = "1.0"

[patch.crates-io]
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", rev = "f7e2b1dbf11e113e258d796288752503a5012367", package = "cosmwasm-std" }

[[bin]]
name = "schema"
required-features = ["schema"]







# [package]
# name = "secret_contract_example"
# version = "0.1.0"
# authors = ["SecretTemplateExample"]
# edition = "2021"

# exclude = [ "contract.wasm", "hash.txt",]

# [lib]
# crate-type = ["cdylib", "rlib"]

# [profile.release]
# opt-level = 3
# debug = false
# rpath = false
# lto = true
# debug-assertions = false
# codegen-units = 1
# panic = 'abort'
# incremental = false
# overflow-checks = true

# [features]
# default = []
# # for quicker tests, cargo test --lib
# # for more explicit tests, cargo test --features=backtraces
# backtraces = ["cosmwasm-std/backtraces"]
# schema = ["cosmwasm-schema"]

# [dependencies]
# cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", rev = "f7e2b1dbf11e113e258d796288752503a5012367" }
# cosmwasm-storage = { git = "https://github.com/scrtlabs/cosmwasm", rev = "f7e2b1dbf11e113e258d796288752503a5012367" }
# schemars = { version = "0.8.11" }
# serde = { version = "1.0" }
# thiserror = { version = "1.0" }
# cosmwasm-schema = {version = "1.0.0", optional = true}
# cw-storage-plus = { version = "0.14.0", default-features = false }

# # Uncomment these for some common extra tools
# # secret-toolkit = { git = "https://github.com/scrtlabs/secret-toolkit", tag = "v0.8.0" }
# # cw-storage-plus = { version = "1.0.1", default-features = false }

# [patch.crates-io]
# # uncomment this if you use cw-storage-plus
# # cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", tag = "v1.1.9-secret" }
# secret-toolkit-crypto = { version = "0.6.0", features = ["rand", "hash"]}
# base32 = "0.4.0"

# [[bin]]
# name = "schema"
# required-features = ["schema"]
